version: '3.5'

services:
  
  # Frontend service
  frontend:
    image: frontend
    ports:
      - 5000:5000
    container_name: frontend

  # Backend + Redis services
  backend:
    image: backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=example
    depends_on:
      - redis
      - db
    container_name: backend

  redis:
    image: redis
    container_name: redis
  
  # Database service
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data
    privileged: true
    environment:
      POSTGRES_PASSWORD: example
    container_name: db_backend

  # Nginx service
  proxy:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    privileged: true
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
    container_name: webserver

volumes:
  database:
  nginx.conf:
