version: '3.5'

services:
  
  frontend:
    image: frontend
    ports:
      - 5000:5000
    container_name: frontend

  backend:
    image: backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=example
    container_name: backend

  redis:
    image: redis
    container_name: redis

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    container_name: db_backend
